#ifndef DEFINE_HPP
#define DEFINE_HPP

#define SCREENX 1280
#define SCREENY 920
#define FRAMELIMIT 60
#define PLAYER_RADIUS 58.5
#define PLAYER_JUMP 30
#define BALL_RADIUS 32
#define GRAVITATION 1.8

#endif DEFINE_HPP
